name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_messaging:
    path: ../
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  http: ^0.13.0

dependency_overrides:
  _flutterfire_internals:
    path: ../../../_flutterfire_internals
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web
  firebase_messaging:
    path: ../
  firebase_messaging_platform_interface:
    path: ../../firebase_messaging_platform_interface
  firebase_messaging_web:
    path: ../../firebase_messaging_web
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.1.3

flutter:
  uses-material-design: true
