name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  http: ^0.13.0

dependency_overrides:
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.1.3

flutter:
  uses-material-design: true
